### ISSUE TITLE
:object-key-type 'symbol as a default

### ISSUE THREAD

**Issue by conao3** [zkry/yaml.el#13]
This issue related #12, I want to suggest `:object-key-type 'symbol` as a default.

Since alist-get usually searches for keys in eql, you need to specify `TESTFN` to use a string as a key. This is not friendly.
On the other hand, `plist-get` does not yet allow us to specify a `TESTFN`. Symbolic keys are more in line with Elisp culture.

```elisp
(let ((yaml "
uri: https://www.google.co.jp
user: foo
password: password
"))
  (alist-get "uri" (yaml-parse-string yaml :object-type 'alist) nil nil #'string=))
;;=> "https://www.google.co.jp"
```
```elisp
(let ((yaml "
uri: https://www.google.co.jp
user: foo
password: password
"))
  (plist-get "url" (yaml-parse-string yaml :object-type 'plist)))
;;=> nil
```

**Comment by zkry** [comment]
I definitely agree with this. With my goal of basing yaml-parse's API off of json-parse function, this behavior difference is definitely wrong. I think for these various object types using strings instead of symbols could even be considered a bug.  Interestingly, using `:object-type 'plist` with `json-parse-string` actually returns a keyword:

```
(json-parse-string "{\"one\": 1}")
;; => #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("one" 1))

(json-parse-string "{\"one\": 1}" :object-type 'alist)
;; => ((one . 1))

(json-parse-string "{\"one\": 1}" :object-type 'plist)
;; => (:one 1)

```

Perhaps I should mimic this behavior by returning keywords for plists as well.
